variables:
  CI_DEBUG_TRACE: "false"

cache:
  paths:
    - maven.repository/

stages:
  - build
  - docker
  - compose

docker-stuff:
  stage: docker
  image: gitlab/dind:latest
  allow_failure: true
  script:
    - docker --version

docker-compose-stuff:
  stage: compose
  image: docker/compose:1.24.0-rc3
  allow_failure: true
  script:
    - docker-compose -d -f e2e/docker-compose.yml up
    - sleep 5
  after_script:
    - set +e
    - docker-compose -f e2e/docker-compose.yml down -v --remove-orphans --rmi all

build-docs:
  #image: $CI_REGISTRY/pxc-gitlab-maven:stable
  stage: build
  script:
    - echo "I'm building the docs while you wait"

build-code:
  #image: $CI_REGISTRY/pxc-gitlab-maven:stable
  stage: build
  allow_failure: true
  script:
    - mvn -U -Dmaven.repo.local=maven.repository --batch-mode -pl e2e -P e2e -am -Dtest=RestAssuredTest -DskipTests test
